name: deploy-lambda
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install --no-cache-dir -r requirements.txt
          
        working-directory: ./Back-end/lambda/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.GITACTIONS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GITACTIONS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run tests
        run: |
          python -m unittest discover

        working-directory: ./Back-end/lambda/


      - name: Create zip file
        run: |
          zip -r func.zip myfunc.py
        working-directory: ./Back-end/lambda
      


      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code --function-name myfunc --zip-file fileb://./Back-end/lambda/func.zip
